id: IDF4A97F2
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T10:44:00.247795'
last_modified: '2022-06-19T10:44:00.247866'
parser: null
source_metadata:
  title: Hagiography of Mus chen dKon mchog rgyal mtshan (1388–1469); Lamdre Lobshe,
    vol. ka, title no. 24
  author: dge slong bsod nams seng ge
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2013-08-20); converted from external file, unrevised, spell-checked, thematic
    TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/377
  bases:
    b85c:
      title: Hagiography of Mus chen dKon mchog rgyal mtshan (1388–1469); Lamdre Lobshe,
        vol. ka, title no. 24
      order: 1
      base_file: b85c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
